config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :locations
  resources :bookings
  resources :researchs
  root to: 'researchs#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :location
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
end

app/models/research.rb
class Research < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :locations, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^researchs$)|(^bookings$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.save

    if @booking.save
      redirect_to booking_path(@booking), notice: 'New booking successfully created!'
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

    redirect_to booking_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to locations_path
  end

  private

  def booking_params
    params.require(:booking).permit(:arrival, :departure, :number_of_rooms, :number_of_people, :location_id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def new
    @location = Location.new
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.save
    authorize @location

    if @location.save
      redirect_to location_path(@location), notice: 'New location successfully created!'
    else
      render :new
    end
  end

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
    authorize @location
  end

  def edit
    @location = Location.find(params[:id])
    authorize @location
  end

  def update
    @location = Location.find(params[:id])
    @location.update(location_params)

    redirect_to location_path(@location)
    authorize @location
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_path
    authorize @location
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :city, :country, :number_of_rooms, :capacity, :price_per_night, :rating, :description, :zip_code, :currency, :capacity_activity_room)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/researchs_controller.rb
class ResearchsController < ApplicationController
  def index
  end

  def home

  end

  def new
    @research = Reserach.new
  end

  def create
   @research = Research.new(research_params)
  if @research.save
   redirect_to research_path(@research)
  else
   render 'index'
  end
 end

  def show
  @research = Research.find(params[:id])
 end

 private

 def research_params
   params.require(:research).permit(:arrival, :departure, :city)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/researchs_helper.rb
module ResearchsHelper
end

app/views/bookings/index.html.erb
<h2>All bookings</h2>

<a class="btn btn-flat" href='/bookings/new'>New Booking</a>
<a class="btn btn-flat" href='/'>Home</a>

<div class="flex-container">
   <% @bookings.each do |booking| %>
   <div class="flex-item">
    <div class="card-trip">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
      <div class="card-trip-infos">
        <div>
          <h2> <%= booking.location.name %></h2>
          <p><%= booking.arrival  %></p>
          <p><%= booking.departure  %></p>
        </div>
        <h2 class="card-trip-pricing">Price/ Night:</h2>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      </div>
    </div>
    </div>
    <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5">
<h2>New Booking</h2>
<%= link_to "index", locations_path  %>
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :arrival %>
  <%= f.input :departure %>
  <%= f.input :number_of_people %>
  <%= f.input :number_of_rooms %>
  <%= f.input :location_id %>

  <%= f.submit %>
<% end %>

</div>

app/views/bookings/show.html.erb
<div class="container mt-5">
  <div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2> <%= @booking.location.name %></h2>
      <p> <%= @booking.arrival %></p>
      <p><%= @booking.departure %></p>

      <%= link_to "index", bookings_path %>
          <%= link_to " edit", edit_booking_path %>
        <%= link_to " delete",
          booking_path(@booking),
                    method: :delete,
                    data: { confirm: "Are you sure?"} %>
    </div>
    <h2 class="card-trip-pricing">Price/ Night: <%= @booking.location.price_per_night %></h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YogaBee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/locations/edit.html.erb
<div class="container mt-5">
<h2>Update Yoga Location</h2>
<%= link_to "index", locations_path  %>
<%= simple_form_for(@location) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :zip_code %>
  <%= f.input :city %>
  <%= f.input :number_of_rooms %>
  <%= f.input :capacity %>
  <%= f.input :price_per_night %>
  <%= f.input :currency %>
  <%= f.input :capacity_activity_room %>
  <%= f.input :description %>

  <%= f.submit %>
<% end %>

</div>

app/views/locations/index.html.erb
<div class="container mt-5">
  <h2>All Our Available destinations</h2>
  <a class="btn btn-flat" href='/locations/new'>New Location</a>
  <a class="btn btn-flat" href='/'>Home</a>

  <div class="flex-container">
    <% @locations.each do |location| %>
    <div class="flex-item">
    <div class="card-trip">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
      <div class="card-trip-infos">
        <div>
          <h2> <%= link_to location.name, location_path(location) %></h2>
          <p><%= location.city %></p>
          <p><%= location.country %></p>
          <p>Rooms: <%= location.number_of_rooms %></p>
        </div>
        <h2 class="card-trip-pricing">Price/ Night: <%= location.price_per_night %></h2>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      </div>
      </div>
    </div>
    <% end %>
    </div>
</div>

app/views/locations/new.html.erb
<div class="container mt-5">
<h2>New Yoga Location Registration</h2>
<%= link_to "index", locations_path  %>
<%= simple_form_for(@location) do |f| %>
  <%= f.input :name, hint: "Enter something catchy" %>
  <%= f.input :address %>
  <%= f.input :zip_code %>
  <%= f.input :city %>
  <%= f.input :country, as: :country %>
  <%= f.input :number_of_rooms %>
  <%= f.input :capacity %>
  <%= f.input :price_per_night %>
  <%= f.input :currency, collection: ['Euro', 'Chf', 'Dollars'] %>
  <%= f.input :capacity_activity_room %>
  <%= f.input :description %>


  <%= f.submit %>
<% end %>

</div>

app/views/locations/show.html.erb
<div class="container mt-5">
  <div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2> <%= @location.name %></h2>
      <p> <%= @location.address %></p>
      <p><%= @location.city %></p>
      <p><%= @location.country %></p>
      <p>Rooms: <%= @location.number_of_rooms %></p>
      <p>Capacity: <%= @location.capacity %> Pax</p>
      <p>User: <%= @location.user %></p>
      <p><%= @location.description %></p>

      <%= link_to "index", locations_path %>
        <% if policy(@location).edit? %>
          <%= link_to " edit", edit_location_path %>
        <% end %>
        <% if policy(@location).destroy? %>
        <%= link_to " delete",
          location_path(@location),
                    method: :delete,
                    data: { confirm: "Are you sure?"} %>
        <% end %>
    </div>
    <h2 class="card-trip-pricing">Price/ Night: <%= @location.price_per_night %></h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>
</div>

app/views/researchs/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(/assets/fontaine.jpg);">
  <div class="container">
    <h1>Organise your next <strong>retreat</strong> with <strong>Yoga Bee</strong>!</h1>
    <p>Don't waste time looking for the right place, it is right here</p>
    <br>
      <div class="container">
        <%= render 'shared/form' %>
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="container">
    <p>Choose your dates</p>
    <%= form_with(url: "/process_dates") do %>
        <div class="row">
            <div class="border">
                <%= text_field_tag 'first_date', "Arrival date", class: 'flatpickr' %>
            </div>
            <div class="col-md-auto">   </div>
            <div class="border">
                <%= text_field_tag 'second_date', "Departure date", class: 'flatpickr' %>
            </div>
        </div>
        <div class="row"><div> </div></div>
        <div class="row">
          <br>
            <div>
                <%= submit_tag("Submit dates", class: "btn btn-primary btn-dates", data: {tooltip_display: :true, placement: :bottom})  %>
            </div>
            <div class="col-md-auto"> </div>
            <div>
                <%= submit_tag("See all properties", class: "btn btn-primary", data: {tooltip_display: :true, placement: :bottom})  %>
            </div>
        </div>
        <div class="col-md-auto">   </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" >
  <%= link_to locations_path, class: "navbar-brand" do %>
    <%= image_tag "Logo_YogaWK.png", id: "logo" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "New booking", new_booking_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Bookings", bookings_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "index", locations_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "Avatar.jpg", class: "avatar dropdown-toggle", id: "avatar1",
        id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log-out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else  %>
      <li class="nav-item">
        <%= link_to "log-in", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>